version: '3.8'

services:
  crypto-news-scraper:
    build: .
    container_name: crypto-news-scraper
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  default:
    name: crypto-network
